%% Foc_2024b - Calibration Parameters
% Auto-generated by exportCalToExcel.m on 18-Jun-2026 22:57:24
% Run this script to load all calibration values into workspace.

%% cal_s16Inductivity
% Inductivity
cal_s16Inductivity = Simulink.Parameter;
cal_s16Inductivity.Value = 0;  % TODO: set actual value
cal_s16Inductivity.DataType = 'int16';
cal_s16Inductivity.CoderInfo.StorageClass = 'Custom';
cal_s16Inductivity.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16RPha
% RPha
cal_s16RPha = Simulink.Parameter;
cal_s16RPha.Value = 0;  % TODO: set actual value
cal_s16RPha.DataType = 'int16';
cal_s16RPha.CoderInfo.StorageClass = 'Custom';
cal_s16RPha.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16LpfPllEst
% LpfPllEst
cal_s16LpfPllEst = Simulink.Parameter;
cal_s16LpfPllEst.Value = 0;  % TODO: set actual value
cal_s16LpfPllEst.DataType = 'int16';
cal_s16LpfPllEst.CoderInfo.StorageClass = 'Custom';
cal_s16LpfPllEst.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16LpfPllEstOpenLoop
% LpfPllEstOpenLoop
cal_s16LpfPllEstOpenLoop = Simulink.Parameter;
cal_s16LpfPllEstOpenLoop.Value = 0;  % TODO: set actual value
cal_s16LpfPllEstOpenLoop.DataType = 'int16';
cal_s16LpfPllEstOpenLoop.CoderInfo.StorageClass = 'Custom';
cal_s16LpfPllEstOpenLoop.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16OmegaGainEst
% OmegaGainEst
cal_s16OmegaGainEst = Simulink.Parameter;
cal_s16OmegaGainEst.Value = 0;  % TODO: set actual value
cal_s16OmegaGainEst.DataType = 'int16';
cal_s16OmegaGainEst.CoderInfo.StorageClass = 'Custom';
cal_s16OmegaGainEst.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtDutyU
% HwtDutyU
cal_HwtDutyU = Simulink.Parameter;
cal_HwtDutyU.Value = 0;  % TODO: set actual value
cal_HwtDutyU.DataType = 'Inherit: auto';
cal_HwtDutyU.CoderInfo.StorageClass = 'Custom';
cal_HwtDutyU.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtDutyV
% HwtDutyV
cal_HwtDutyV = Simulink.Parameter;
cal_HwtDutyV.Value = 0;  % TODO: set actual value
cal_HwtDutyV.DataType = 'Inherit: auto';
cal_HwtDutyV.CoderInfo.StorageClass = 'Custom';
cal_HwtDutyV.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtDutyW
% HwtDutyW
cal_HwtDutyW = Simulink.Parameter;
cal_HwtDutyW.Value = 0;  % TODO: set actual value
cal_HwtDutyW.DataType = 'Inherit: auto';
cal_HwtDutyW.CoderInfo.StorageClass = 'Custom';
cal_HwtDutyW.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtSector
% HwtSector
cal_HwtSector = Simulink.Parameter;
cal_HwtSector.Value = 0;  % TODO: set actual value
cal_HwtSector.DataType = 'Inherit: auto';
cal_HwtSector.CoderInfo.StorageClass = 'Custom';
cal_HwtSector.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_bActHwMode
% ActHwMode
cal_bActHwMode = Simulink.Parameter;
cal_bActHwMode.Value = 0;  % TODO: set actual value
cal_bActHwMode.DataType = 'boolean';
cal_bActHwMode.CoderInfo.StorageClass = 'Custom';
cal_bActHwMode.CoderInfo.CustomStorageClass = 'CAL_NORMAL_8BIT';

%% cal_s16MinSampleTime
% MinSampleTime
cal_s16MinSampleTime = Simulink.Parameter;
cal_s16MinSampleTime.Value = 0;  % TODO: set actual value
cal_s16MinSampleTime.DataType = 'int16';
cal_s16MinSampleTime.CoderInfo.StorageClass = 'Custom';
cal_s16MinSampleTime.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

