%% Foc_2024b - Calibration Parameters
% Auto-generated by exportCalToExcel.m on 18-Jun-2026 23:59:23
% Run this script to load all calibration values into workspace.

%% cal_AdcMaxCountsHw
% AdcMaxCountsHw
cal_AdcMaxCountsHw = Simulink.Parameter;
cal_AdcMaxCountsHw.Value = 0;  % TODO: set actual value
cal_AdcMaxCountsHw.DataType = 'Inherit: auto';
cal_AdcMaxCountsHw.CoderInfo.StorageClass = 'Custom';
cal_AdcMaxCountsHw.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_AdcRefVoltHw
% AdcRefVoltHw
cal_AdcRefVoltHw = Simulink.Parameter;
cal_AdcRefVoltHw.Value = 0;  % TODO: set actual value
cal_AdcRefVoltHw.DataType = 'Inherit: auto';
cal_AdcRefVoltHw.CoderInfo.StorageClass = 'Custom';
cal_AdcRefVoltHw.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_OhmRShuntHw
% OhmRShuntHw
cal_OhmRShuntHw = Simulink.Parameter;
cal_OhmRShuntHw.Value = 0;  % TODO: set actual value
cal_OhmRShuntHw.DataType = 'Inherit: auto';
cal_OhmRShuntHw.CoderInfo.StorageClass = 'Custom';
cal_OhmRShuntHw.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_GainAmpHw
% GainAmpHw
cal_GainAmpHw = Simulink.Parameter;
cal_GainAmpHw.Value = 0;  % TODO: set actual value
cal_GainAmpHw.DataType = 'Inherit: auto';
cal_GainAmpHw.CoderInfo.StorageClass = 'Custom';
cal_GainAmpHw.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_AdcVoltMidHw
% AdcVoltMidHw
cal_AdcVoltMidHw = Simulink.Parameter;
cal_AdcVoltMidHw.Value = 0;  % TODO: set actual value
cal_AdcVoltMidHw.DataType = 'Inherit: auto';
cal_AdcVoltMidHw.CoderInfo.StorageClass = 'Custom';
cal_AdcVoltMidHw.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_FullScaleCur
% FullScaleCur
cal_FullScaleCur = Simulink.Parameter;
cal_FullScaleCur.Value = 0;  % TODO: set actual value
cal_FullScaleCur.DataType = 'Inherit: auto';
cal_FullScaleCur.CoderInfo.StorageClass = 'Custom';
cal_FullScaleCur.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_u8TiDebPhaCur
% TiDebPhaCur
cal_u8TiDebPhaCur = Simulink.Parameter;
cal_u8TiDebPhaCur.Value = 0;  % TODO: set actual value
cal_u8TiDebPhaCur.DataType = 'uint8';
cal_u8TiDebPhaCur.CoderInfo.StorageClass = 'Custom';
cal_u8TiDebPhaCur.CoderInfo.CustomStorageClass = 'CAL_NORMAL_8BIT';

%% cal_s16ThresholdPhaCurImplaisible
% ThresholdPhaCurImplaisible
cal_s16ThresholdPhaCurImplaisible = Simulink.Parameter;
cal_s16ThresholdPhaCurImplaisible.Value = 0;  % TODO: set actual value
cal_s16ThresholdPhaCurImplaisible.DataType = 'int16';
cal_s16ThresholdPhaCurImplaisible.CoderInfo.StorageClass = 'Custom';
cal_s16ThresholdPhaCurImplaisible.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16Inductivity
% Inductivity
cal_s16Inductivity = Simulink.Parameter;
cal_s16Inductivity.Value = 0;  % TODO: set actual value
cal_s16Inductivity.DataType = 'int16';
cal_s16Inductivity.CoderInfo.StorageClass = 'Custom';
cal_s16Inductivity.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16RPha
% RPha
cal_s16RPha = Simulink.Parameter;
cal_s16RPha.Value = 0;  % TODO: set actual value
cal_s16RPha.DataType = 'int16';
cal_s16RPha.CoderInfo.StorageClass = 'Custom';
cal_s16RPha.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16LpfPllEst
% LpfPllEst
cal_s16LpfPllEst = Simulink.Parameter;
cal_s16LpfPllEst.Value = 0;  % TODO: set actual value
cal_s16LpfPllEst.DataType = 'int16';
cal_s16LpfPllEst.CoderInfo.StorageClass = 'Custom';
cal_s16LpfPllEst.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16LpfPllEstOpenLoop
% LpfPllEstOpenLoop
cal_s16LpfPllEstOpenLoop = Simulink.Parameter;
cal_s16LpfPllEstOpenLoop.Value = 0;  % TODO: set actual value
cal_s16LpfPllEstOpenLoop.DataType = 'int16';
cal_s16LpfPllEstOpenLoop.CoderInfo.StorageClass = 'Custom';
cal_s16LpfPllEstOpenLoop.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_s16OmegaGainEst
% OmegaGainEst
cal_s16OmegaGainEst = Simulink.Parameter;
cal_s16OmegaGainEst.Value = 0;  % TODO: set actual value
cal_s16OmegaGainEst.DataType = 'int16';
cal_s16OmegaGainEst.CoderInfo.StorageClass = 'Custom';
cal_s16OmegaGainEst.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtDutyU
% HwtDutyU
cal_HwtDutyU = Simulink.Parameter;
cal_HwtDutyU.Value = 0;  % TODO: set actual value
cal_HwtDutyU.DataType = 'Inherit: auto';
cal_HwtDutyU.CoderInfo.StorageClass = 'Custom';
cal_HwtDutyU.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtDutyV
% HwtDutyV
cal_HwtDutyV = Simulink.Parameter;
cal_HwtDutyV.Value = 0;  % TODO: set actual value
cal_HwtDutyV.DataType = 'Inherit: auto';
cal_HwtDutyV.CoderInfo.StorageClass = 'Custom';
cal_HwtDutyV.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtDutyW
% HwtDutyW
cal_HwtDutyW = Simulink.Parameter;
cal_HwtDutyW.Value = 0;  % TODO: set actual value
cal_HwtDutyW.DataType = 'Inherit: auto';
cal_HwtDutyW.CoderInfo.StorageClass = 'Custom';
cal_HwtDutyW.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_HwtSector
% HwtSector
cal_HwtSector = Simulink.Parameter;
cal_HwtSector.Value = 0;  % TODO: set actual value
cal_HwtSector.DataType = 'Inherit: auto';
cal_HwtSector.CoderInfo.StorageClass = 'Custom';
cal_HwtSector.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

%% cal_bActHwMode
% ActHwMode
cal_bActHwMode = Simulink.Parameter;
cal_bActHwMode.Value = 0;  % TODO: set actual value
cal_bActHwMode.DataType = 'boolean';
cal_bActHwMode.CoderInfo.StorageClass = 'Custom';
cal_bActHwMode.CoderInfo.CustomStorageClass = 'CAL_NORMAL_8BIT';

%% cal_s16MinSampleTime
% MinSampleTime
cal_s16MinSampleTime = Simulink.Parameter;
cal_s16MinSampleTime.Value = 0;  % TODO: set actual value
cal_s16MinSampleTime.DataType = 'int16';
cal_s16MinSampleTime.CoderInfo.StorageClass = 'Custom';
cal_s16MinSampleTime.CoderInfo.CustomStorageClass = 'CAL_NORMAL_16BIT';

