% -------------------------------------------------------------------
%  Generated by MATLAB on 22-July-2025
%  MATLAB version: (R2024b)
% -------------------------------------------------------------------

clear all; bdclose all; clear classes;

% add library path which need to be updated
%addpath('C:\Users\uiv34654\OneDrive - Vitesco Technologies\Desktop\BMS_Software\SOCwith2RC');
setenv('SWC_NAME', 'HORN');

sl_refresh_customizations;

% load parameters which need to be updated
load('Atom_BCM_SeatFLProvider.mat');
Seat_Enums;
Seat_LoadCalParameter;

% load model which need to be updated
Atom_BCM_SeatFLProvider;

% load configuration file which need to be updated
Simulink.BlockDiagram.loadActiveConfigSet('Atom_BCM_SeatFLProvider', 'ModelConfigCommon_v08.m')

set_param('Atom_BCM_SeatFLProvider', 'MemSecPackage', 'NoneSAR');

set_param('Atom_BCM_SeatFLProvider', 'MemSecFuncExecute', 'CODE');

set_param('Atom_BCM_SeatFLProvider', 'MemSecDataInternal', 'DATA');

set_param('Atom_BCM_SeatFLProvider', 'MemSecDataConstants', 'CONST_DATA');